release
lammer90/gofermart_2 pull request #1
Opened 2023-12-23 19:58 UTC by lammer90

+ release

2023-12-28 09:46 UTC, rktkov requested changes

2023-12-28 09:46 UTC, rktkov commented on cmd/gophermart/main.go
> +	"database/sql"
Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2023-12-28 09:46 UTC, rktkov commented on cmd/gophermart/main.go
> +	cookieStore := buildSession()
Я бы добавил еще  один уровень, который бы назвал app и в него бы спрятал из main - все что касается веба (инициализацию роутера, все сервисов и запуск "прослушивания"). А тут бы оставил конфиг, логгер, запуск сервиса-бонусов и запуск app)

2023-12-28 09:46 UTC, rktkov commented on cmd/gophermart/main.go
> +	go accrualservice.New(orderSrv, config.AccrualAddress).Start()
Горутина запускается без передачи контекста. А как будем ее останавливать при необходимости?

2023-12-28 09:46 UTC, rktkov commented on internal/services/accrualservice/accrualservice.go
> +	"go.uber.org/zap"
Наличие в импортах и внутреннего пакета логгирования и внешнего пакета - указание, что где-то в архитектуре протекла зависимость. Во внутреннем пакета стоит сделать "фасадные" методы логгирования, которые в сигнатурах используеют базовые типы. И внутри этих методов оборачивать все что нужно структурами из внешней библиотеки.

2023-12-28 09:46 UTC, rktkov commented on internal/web/handlers/authhandler/authhandler.go
> +package authhandler
Я бы убрал слово handler из названия пакета. Пакет на уровень выше уже называется handlers. Получается излишнее дублирование.

2024-01-10 19:52 UTC, lammer90 commented on cmd/gophermart/main.go
> +	"database/sql"
поправил

2024-01-10 19:52 UTC, lammer90 commented on cmd/gophermart/main.go
> +	cookieStore := buildSession()
добавил

2024-01-10 19:53 UTC, lammer90 commented on cmd/gophermart/main.go
> +	go accrualservice.New(orderSrv, config.AccrualAddress).Start()
добавил

2024-01-10 19:53 UTC, lammer90 commented on internal/services/accrualservice/accrualservice.go
> +	"go.uber.org/zap"
поправил

2024-01-10 19:53 UTC, lammer90 commented on internal/web/handlers/authhandler/authhandler.go
> +package authhandler
у меня уже есть пакет auth

2024-01-12 21:31 UTC, rktkov approved these changes

2024-02-18 17:40 UTC, merged